- yum:
    name: nginx
    state: latest

- shell: rm /etc/nginx/conf.d/*

- command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old

- copy:
    src: conf
    dest: /etc/nginx/nginx.conf

- copy:
    src: load-balancer
    dest: /etc/nginx/conf.d/load-balancer.conf
  notify: restart nginx
